### PR TITLE
19 dockerize project

### LINKED ISSUE #19: Dockerize Project
Package components as Docker containers with a Docker-Compose.yaml orchestration script

This should use the scale parameter on up to be able to scale the nodes up and down
- dc up --scale 2
- dc up --scale 3

### LINKED ISSUE #35: Client check will erroneously fail when id is 0
if (elem && bigBucketOfData[elem] && bigBucketOfData[elem].successor && bigBucketOfData[elem].successor.id && bigBucketOfData[elem].successor.id !== lastNode.id) {

We likely don't need the first test

### PR DESCRIPTION
**Pull request by bushidocodes**
Resolves #19 
Resolves #35

This PR does the following
* Creates an initial `docker-compose` setup. On a system running Docker, this can be started with `docker-compose up`. The UI is accessible at localhost:1337 as before
* Refactors out the old gRPC client in client.js and refactors the crawler into a JS Class.
* Changes the meaning of the `ip` argument to mean the publicly-addressable hostname. The node's have no idea how they're networked, so they don't have the ability to bind to a specific IP port. We bind them to 0.0.0.0 (all interfaces) at the port we specify, and we tell them their hostname so they respond with something other nodes can use to reach them.

### CODE REVIEW

File: node.js [hunk 1]
```diff
@@ -386,7 +386,7 @@ async function find_successor(id, node_querying, node_queried) {
   } else {
     // create client for remote call
     const node_queried_client = caller(
-      `localhost:${node_queried.port}`,
+      `${node_queried.ip}:${node_queried.port}`,
```
Comment (albero94) [inline node.js:389]: Great! Now we don't have the ip hardcoded.

File: client.js [hunk 2]
```diff
@@ -102,67 +82,98 @@ async function insert({ _, ...rest }) {
...
+  constructor(ip, port, stepInSeconds) {
+    this.ip = ip;
+    this.port = port;
+    this.state = {};
+    this.ring = new Set([]);
+    setInterval(async () => {
+      await this.crawl();
+    }, stepInSeconds);
+  }
+  static buildConnectionString(ip, port) {
```
Comment (albero94) [inline client.js]: Is it really cleaner to have this method instead of just concatanating in the two places that is necessary? (humble question)

File: client.js [hunk 3]
```diff
@@ -102,67 +82,98 @@ async function insert({ _, ...rest }) {
...
+            delete this.state[storedConnectionString];
           }
         }
-        ring.clear();
+        // Clear because we are starting a new walk around the overlay network
+        this.ring.clear();
+      } else {
+        // Add the node to the walk
+        this.ring.add(connectionString);
       }
```
Comment (albero94) [inline client.js]: Maybe put this into a function with a meaningful name instead of having that long comment?

**Review by albero94 — COMMENTED** [review]
Sean made me a demo for the docker piece and it looked great!

Also the refactored code looks much better organised. I have left some comments trying to give my view point. You can take a look, change some of them or not and let me know.

**Review by albero94 — CHANGES_REQUESTED** [review]
Take a look at my comments above.

**Review by albero94 — APPROVED** [review]
Thanks for making the changes!
