### PR TITLE
14 leave

### LINKED ISSUE #29: [chord] implement confirm_exist()
It is still kind of a dummy call.

### LINKED ISSUE #31: [chord] improve handling of nodes dropping - ungracefully - from the chord
successor to issue #10 .

currently, if too many nodes are crushed in rapid succession, it fails to stabilize.

see details in issue #10  for hints as to what else to add.

### LINKED ISSUE #66: [chord] handle join() collisions
if a node that would hash to the ID of an existing node tries to join, that has to be handled.  easiest way would be to just reject the new node.

### PR DESCRIPTION
**Pull request by heidiklum**
Resolves #66 
Resolves #29 
Resolves #31 

the original intention was to implement a graceful 'leave' function. however, in becoming familiar with the code, it was safer to implement the collision-avoidance feature to close issue #66 . in order to do that, i front-ported the confirmExist that i had worked on the pre-class branch to also close issue #29 . in other words, the name of the branch is not good but i believe the branch itself is.

in particular, i believe it does close issue #31 , which is related to leaving in that now the "ungraceful" leaving of nodes (e.g., when you just "ctrl+c" some nodes) works much more robustly.  You can still cause hurt but it does work MUCH better, to include the problem with "last-node-standing" is now stable.  In fact, you can actually add nodes to last-node-standing and then kill one of the two, then add some more.

The code was tested in "node node", "npm run" and docker-compose modes.  The first two work a bit better in that docker-compose scale-down is SO fast that it's just hard to keep up.  You can notice this in that the picture will often show the 'primary' missing, which is obviously not true.  But, much better than before and sets us up for the .... elusive 'graceful' leave :-)

beyond adding functionality, a big departure is that i clobbered the handling of the "known" as a property of the class.

i'll then have to come back to a new branch to deal with what i really wanted to deal with :-)

happy thanksgiving!!

### CODE REVIEW

File: app/node.js [hunk 1]
```diff
@@ -72,34 +99,23 @@ async function main() {
...
   try {
     userServiceNode = new UserService({ ...args });
     await userServiceNode.serve();
-    await userServiceNode.joinCluster();
+    let knownNode = {
+      id: knownNodeId,
+      host: knownNodeHost,
+      port: knownNodePort
+    };
+    await userServiceNode.joinCluster(knownNode);
```
Comment (bushidocodes) [inline app/node.js:118]: This is nice! The API makes much more sense shifting these values to the joinCluster method. Out of curiosity, why do we need `knownNodeId` at this point? Wouldn't we ask this known node for this information in all circumstances?

**Review by bushidocodes — APPROVED** [review]
Tested, and the chord does seem to handle dropping nodes much better! I was able to scale up to 25 secondary nodes and then back down to 0 secondary nodes (only the primary node remaining). I have a comment about the need for passing in the knownNode ID and why we still need that, but if you think that's behavior we can drop, we can do that in a separate issue. Thanks for the work here! 👏👏

File: app/node.js (hunk 1 above)
Comment (heidiklum) [reply app/node.js:118]: I just put a comment in with a lengthy explanation but then accidentally delete it.  Bottom line is, yes, I tend to agree with you even though it was an oversight that I forgot to put the logic of handling the argument-provided knownId.  I'll go ahead and merge "as is" but happy to either remove the argument or add the logic if any team member wants to keep that option.  I definitely think we want to keep the option of forcing the "self" ID but can't see why we wouldn't always just ask the known node, as we are doing currently in join().
